# Generated by Django 5.2.6 on 2026-02-15 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='event_date',
            field=models.DateTimeField(blank=True, help_text='Optional: If this is an event, set the date and time.', null=True),
        ),
    ]
