# Generated by Django 5.2.6 on 2026-02-15 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_announcement_event_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cleaninggroup',
            name='members',
        ),
    ]
