# Generated by Django 5.2.6 on 2026-02-15 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='user',
            name='payment_status',
            field=models.CharField(choices=[('not_paid', 'Not Paid'), ('partially_paid', 'Partially Paid'), ('fully_paid', 'Fully Paid')], default='not_paid', max_length=20, verbose_name='Payment Status'),
        ),
    ]
