# Generated by Django 5.2.6 on 2026-02-15 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_remove_cleaninggroup_members'),
        ('users', '0002_remove_user_is_paid_user_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cleaning_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='scheduling.cleaninggroup'),
        ),
    ]
