# Generated by Django 5.2.6 on 2026-02-17 07:59

from django.db import migrations, models

def split_full_name(apps, schema_editor):
    User = apps.get_model('users', 'User')
    for user in User.objects.all():
        parts = user.full_name.split()
        if len(parts) == 1:
            user.first_name = parts[0]
            user.last_name = ''
        elif len(parts) == 2:
            user.first_name = parts[0]
            user.last_name = parts[1]
        else:
            user.first_name = parts[0]
            user.middle_name = ' '.join(parts[1:-1])
            user.last_name = parts[-1]
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_cleaning_group'),
    ]

    operations = [
        migrations.RunPython(split_full_name),
        migrations.RemoveField(
            model_name='user',
            name='full_name',
        ),
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
    ]