# Generated by Django 5.2.6 on 2026-03-11 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_assignmentrequest'),
        ('users', '0005_user_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='emergency_contact', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('contact_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('relationship', models.CharField(max_length=100, verbose_name='Relationship')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone Number')),
            ],
            options={
                'verbose_name': 'Emergency Contact',
                'verbose_name_plural': 'Emergency Contacts',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='assigned_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to='rooms.room'),
        ),
        migrations.DeleteModel(
            name='Violation',
        ),
    ]
