# Generated by Django 5.2.6 on 2026-03-09 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_cleaninggroup_cleaningschedule'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cleaningschedule',
            unique_together=set(),
        ),
    ]
