# Generated by Django 5.2.6 on 2026-03-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_cleaningschedule_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='event_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
