# Generated by Django 5.2.6 on 2026-02-15 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='floor',
            field=models.IntegerField(choices=[(1, '1st Floor'), (2, '2nd Floor'), (3, '3rd Floor')], default=1),
        ),
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('full', 'Full'), ('maintenance', 'Under Maintenance')], default='available', max_length=20),
        ),
    ]
