# Generated by Django 5.2.6 on 2026-02-15 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_room_floor_room_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='occupancy',
            options={'verbose_name_plural': 'Occupancies'},
        ),
    ]
